spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=hrms;encrypt=true;trustServerCertificate=true
    username: hrms_user
    password: hrms123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

server:
  port: 8080